"""
Automated Report Scheduler & Email Dispatcher.
Triggers shift reports and daily summaries according to plant shift hours.
Optionally emails the generated Excel file via SMTP.
"""

import sys
import yaml
import smtplib
import logging
from pathlib import Path
from email.message import EmailMessage
from datetime import datetime, timedelta
from typing import Optional

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from src.storage.db import DatabaseManager
from src.reports.generator import ExcelReportGenerator

logger = logging.getLogger("ReportScheduler")


class ReportScheduler:
    """Manages scheduled report generation and optional email transmission."""

    def __init__(self, config_path: str = "config/config.yaml"):
        self.config_path = Path(config_path)
        with open(self.config_path, "r") as f:
            self.config = yaml.safe_load(f)

        db_path = self.config.get("storage", {}).get("db_path", "data/pasteurizer_data.db")
        self.db = DatabaseManager(db_path=db_path)
        self.generator = ExcelReportGenerator(
            db_manager=self.db,
            output_dir=self.config.get("reporting", {}).get("output_dir", "reports"),
            plant_info=self.config.get("plant", {})
        )

    def generate_shift_report(self, shift_hours_back: int = 8) -> Optional[Path]:
        """Generate a report for the previous shift window."""
        now = datetime.now()
        start = now - timedelta(hours=shift_hours_back)
        title = f"Shift Report ({shift_hours_back}h Window)"
        step = self.config.get("reporting", {}).get("excel_sample_interval_sec", 1)

        path = self.generator.generate_report(
            start_iso=start.isoformat(),
            end_iso=now.isoformat(),
            report_title=title,
            sample_step=step
        )

        if path and self.config.get("reporting", {}).get("email", {}).get("enabled", False):
            self.send_email(path, title)

        return path

    def generate_daily_report(self) -> Optional[Path]:
        """Generate a 24-hour summary report."""
        now = datetime.now()
        start = now - timedelta(hours=24)
        title = f"Daily 24h Summary ({start.strftime('%Y-%m-%d')})"
        step = self.config.get("reporting", {}).get("excel_sample_interval_sec", 1)

        path = self.generator.generate_report(
            start_iso=start.isoformat(),
            end_iso=now.isoformat(),
            report_title=title,
            sample_step=step
        )

        if path and self.config.get("reporting", {}).get("email", {}).get("enabled", False):
            self.send_email(path, title)

        return path

    def send_email(self, file_path: Path, subject: str) -> bool:
        """Send generated report via SMTP."""
        mail_cfg = self.config.get("reporting", {}).get("email", {})
        if not mail_cfg.get("enabled", False):
            logger.info("Email dispatch disabled in configuration.")
            return False

        try:
            logger.info("Sending report '%s' via SMTP to %s...", file_path.name, mail_cfg.get("recipients"))
            msg = EmailMessage()
            msg["Subject"] = f"[{self.config.get('plant', {}).get('name')}] {subject}"
            msg["From"] = mail_cfg.get("sender")
            msg["To"] = ", ".join(mail_cfg.get("recipients", []))
            msg.set_content(
                f"Attached is the automated process report generated by the 10 KL Pasteurizer Data Logger.\n\n"
                f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
                f"Equipment: {self.config.get('plant', {}).get('unit')}\n"
                f"Report File: {file_path.name}\n"
            )

            with open(file_path, "rb") as f:
                file_data = f.read()
                msg.add_attachment(
                    file_data,
                    maintype="application",
                    subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    filename=file_path.name
                )

            server = mail_cfg.get("smtp_server")
            port = mail_cfg.get("smtp_port", 587)
            use_tls = mail_cfg.get("use_tls", True)

            with smtplib.SMTP(server, port) as smtp:
                if use_tls:
                    smtp.starttls()
                if mail_cfg.get("username") and mail_cfg.get("password"):
                    smtp.login(mail_cfg["username"], mail_cfg["password"])
                smtp.send_message(msg)

            logger.info("Email sent successfully.")
            return True

        except Exception as exc:
            logger.error("Failed to transmit email report: %s", exc)
            return False


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    scheduler = ReportScheduler()

    # If run directly with arguments
    if len(sys.argv) > 1 and sys.argv[1] == "--daily":
        scheduler.generate_daily_report()
    else:
        scheduler.generate_shift_report()
